### PR TITLE
Strict mode in query pattern comparison

### PR DESCRIPTION
**Pull request by smgladkovskiy**
Hi!

I have an issue when i mocked two sql queries: `SELECT * FROM "table"` and `SELECT * FROM "table" WHERE "id" = 1`. FakeResponse for first query sometimes appears in response for second query because of `strings.Contains()` comparison.
I added "strictMatch" for fulltext comparison of queries and avoid previous issue.

### CODE REVIEW

**Review by Selvatico — APPROVED** [review]

**Comment by Selvatico** [comment]
Thnx for the update. Let's merge it. tests are passing.

**Comment by Selvatico** [comment]
@smgladkovskiy for the complete picture can you please add the comment about locking?

**Comment by smgladkovskiy** [comment]
> @smgladkovskiy for the complete picture can you please add the comment about locking?

Sure!
It cause errors and data extractions collisions (wrong results on search statement) while `go test -race -short./...`. Locking solve race problems. Now tests can be run with `t.Parallel()`!

**Review by dzhahaiev — APPROVED** [review]

**Comment by Selvatico** [comment]
@TrueCarry @smgladkovskiy  maybe I am missing something, but race conditions only could happen when you use the same instance of response over several queries or when the same response with the same conditions used in several different tests. Am I right?

**Comment by smgladkovskiy** [comment]
> @TrueCarry @smgladkovskiy maybe I am missing something, but race conditions only could happen when you use the same instance of response over several queries or when the same response with the same conditions used in several different tests. Am I right?
Yep. That's right.
In my case I write tests without coupling with each other, in parallel and they should show predictable results in race tests.

**Comment by TrueCarry** [comment]
@Selvatico, not sure what exactly triggers it. In our tests we initialize db interface and pass it to the function that needs to be tested. But that function can make(and usually do) multiple queries.

**Comment by smgladkovskiy** [comment]
Bumped master changes and make some minor changes in readme.

Still waiting for strict and antirace. :)
☮️

**Comment by Selvatico** [comment]
@vallieres can you take a look into this changes? If not I will merge it. Seems all tests passed and the code is fine. Thnx a lot @smgladkovskiy and sorry for the long delay with communications here.

**Comment by smgladkovskiy** [comment]
@Selvatico @vallieres thanks for your time and work! 🙏

**Pull request merged**
